### ISSUE TITLE
URL for "statusServer" missing port number

### ISSUE THREAD

**Issue by markborkum** [pacifica/pacifica-python-uploader#28]
### Pacifica Python Uploader version
1.0

### Pacifica Core Software versions
n/a

### Platform Details
All supported platforms

### Scenario:
In [test_data/ref/uploader-config.json](https://github.com/pacifica/pacifica-python-uploader/blob/9da261824e602f61cee25f15c3ad8d146fa3a3b8/test_data/ref/uploader-config.json#L123), the URL includes a port number separator (full-colon character ":") but no port number.

### Steps to Reproduce:
n/a

### Expected Result:
n/a

### Actual Result:
n/a

**Comment by dmlb2000** [comment]
This is a won't fix, the uploader-config.json is just a reference from other development efforts...
