### ISSUE TITLE
Make new tests showing how URL parts and auth flow into the policy and uploader objects.

### ISSUE THREAD

**Issue by derekhop** [pacifica/pacifica-python-uploader#29]
### Pacifica Python Uploader version
Master
### Pacifica Core Software versions
Master
### Platform Details
Windows
### Scenario:
Need to show how the authentication and URL parts get set in the policy and uploader objects in a test.
### Steps to Reproduce:
N/A
### Expected Result:
N/A
### Actual Result:
N/A

**Comment by dmlb2000** [comment]
This got fixed by #30
